from selenium import webdriver

driver = webdriver.Chrome('chromedriver')  # Optional argument, if not specified will search path.
#driver.implicitly_wait(30)
driver.maximize_window()
#driver.get("https://www.onlineservices.nsdl.com/paam/")
driver.get("http://localhost/Pan/admin/mainprofile.php?")

#Input field
#search_field = driver.find_element_by_id("search_form_input_homepage")

#Userid
#userfield = driver.find_element_by_id("userID")

areacode = driver.find_element_by_id("areacode")
areacode = driver.find_element_by_id("aotype")
areacode = driver.find_element_by_id("rangecode")
areacode = driver.find_element_by_id("applicanttitle")
areacode = driver.find_element_by_id("lastname")
areacode = driver.find_element_by_id("firstname")
areacode = driver.find_element_by_id("middlename")
areacode = driver.find_element_by_id("panname")
areacode = driver.find_element_by_id("othernameflagyes")
areacode = driver.find_element_by_id("othernameflagno")
areacode = driver.find_element_by_id("aliasapplicanttitle")
areacode = driver.find_element_by_id("aliaslastname")
areacode = driver.find_element_by_id("aliasfirstname")
areacode = driver.find_element_by_id("aliasmiddlename")
areacode = driver.find_element_by_id("gender")
areacode = driver.find_element_by_id("dateofbirth")
areacode = driver.find_element_by_id("fatherlastname")
areacode = driver.find_element_by_id("fatherfirstname")
areacode = driver.find_element_by_id("fathermiddlename")
areacode = driver.find_element_by_id("motherlastname")
areacode = driver.find_element_by_id("motherfirstname")
areacode = driver.find_element_by_id("mothermiddlename")
areacode = driver.find_element_by_id("aonumber")
areacode = driver.find_element_by_id("aonumber")
areacode = driver.find_element_by_id("aonumber")
areacode = driver.find_element_by_id("aonumber")
areacode = driver.find_element_by_id("aonumber")
areacode = driver.find_element_by_id("aonumber")
areacode = driver.find_element_by_id("aonumber")
areacode = driver.find_element_by_id("aonumber")
areacode = driver.find_element_by_id("aonumber")
areacode = driver.find_element_by_id("aonumber")
areacode = driver.find_element_by_id("aonumber")
areacode = driver.find_element_by_id("aonumber")
areacode = driver.find_element_by_id("aonumber")
areacode = driver.find_element_by_id("aonumber")
areacode = driver.find_element_by_id("aonumber")
areacode = driver.find_element_by_id("aonumber")
areacode = driver.find_element_by_id("aonumber")
areacode = driver.find_element_by_id("aonumber")
areacode = driver.find_element_by_id("aonumber")
areacode = driver.find_element_by_id("aonumber")
areacode = driver.find_element_by_id("aonumber")
areacode = driver.find_element_by_id("aonumber")
#search_field.send_keys("Hello World")
#search_field.submit()

